import re
text = open('test.js', encoding='utf-8').read()
text = re.sub(r'//.*', '', text)
text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
text = re.sub(r'\'(?:[^\'\\]|\\.)*\'', '', text)
text = re.sub(r'\"(?:[^\"\\]|\\.)*\"', '', text)
text = re.sub(r'\`(?:[^\`\\]|\\.)*\`', '', text)
print('Braces:', text.count('{'), text.count('}'))
print('Parens:', text.count('('), text.count(')'))
print('Brackets:', text.count('['), text.count(']'))
